apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: dedicated-linux-bond-iface
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""  
  desiredState:
    interfaces:
    - name: bond1
      type: bond
      state: up
      ipv4:
         enabled: false
       ipv6:
         enabled: false
      link-aggregation:
        mode: active-backup
        port:
          - ens4
          - ens5
    - name: ens4
      type: ethernet
      state: up
    - name: ens5
      type: ethernet
      state: up
    - ipv4:
        enabled: false
      ipv6:
        enabled: false
      name: ovsbr1
      state: up
      type: ovs-interface
    - bridge:
        allow-extra-patch-ports: true
        options:
          stp: false
        port:
        - name: ovsbr1
      name: ovsbr1
      state: up
      type: ovs-bridge
    ovn:
      bridge-mappings:
      - bridge: ovsbr1
        localnet: datanet
        state: present

